#!/usr/bin/env python3
def rek(n):
    if n == 1:       #Zad 3 a)
        return 1
    return n**2 + rek(n - 1)


def sziter(n):      #zad 3 b)
    w = 1
    for i in range(2, n + 1):
        w += i ** 2
    return w


#zad3 c)
def suman(n):
    return (n*(n + 1)*(2*n + 1)) // 6



#ZAD 8
slowo = "kajak"
stos = [i for i in slowo] #stos = list(slowo)
kolejka = [i for i in slowo]

print(stos)
print(kolejka)
                         #dokoncz tak zeby sprawdzal do polowy slowa
while len(stos) > 1:
    zs = stos.pop()
    zk = kolejka.pop(0)
    if zs != zk:
        print("Tekst nie jest palindromem")
        stos = ["a"]
    else:
        if len(stos) == 1:
            zs = stos.pop()
            zk = kolejka.pop(0)   
            if zs == zk:
                print(f"Słowo {slowo} jest palindromem")
            else:
                print(f"Słowo {slowo} nie jest palindromem")
                
            
#ZAD 8 ALE TAK JAK POWINNO BYC
def palindrom(n):
	stos = [i for i in n]
	kolejka = [i for i in n]
	
	for i in range(0, len(stos) // 2):    #sprawdzamy do polowy tak jak mialo byc
		if stos.pop() != kolejka.pop(0):
			return False
	return True
	
n = input("Tekst:")
print(palindrom(n))










#print(int(suman(3)))
#print(sziter(3))
