#!/usr/bin/env python3
def rek(n):
    if n == 1:       #Zad 3 a)
        return 1
    return n**2 + rek(n - 1)


def sziter(n):      #zad 3 b)
    w = 1
    for i in range(2, n + 1):
        w += i ** 2
    return w


#zad3 c)
def suman(n):
    return (n*(n + 1)*(2*n + 1)) // 6


'''
#ZAD 8
slowo = "kajak"
stos = [i for i in slowo] #stos = list(slowo)
kolejka = [i for i in slowo]

print(stos)
print(kolejka)
                         #dokoncz tak zeby sprawdzal do polowy slowa
while len(stos) > 1:
    zs = stos.pop()
    zk = kolejka.pop(0)
    if zs != zk:
        print("Tekst nie jest palindromem")
        stos = ["a"]
    else:
        if len(stos) == 1:
            zs = stos.pop()
            zk = kolejka.pop(0)   
            if zs == zk:
                print(f"Słowo {slowo} jest palindromem")
            else:
                print(f"Słowo {slowo} nie jest palindromem")
'''       
            
#ZAD 8 ALE TAK JAK POWINNO BYC
def palindrom(n):
	stos = [i for i in n]
	kolejka = [i for i in n]
	
	for i in range(0, len(stos) // 2):    #sprawdzamy do polowy tak jak mialo byc
		if stos.pop() != kolejka.pop(0):
			return False
	return True
	
n = input("Tekst:")
print(palindrom(n))


#Zad 9 (ONP)
dane = [2, 7, "+", 3, "/", 14, 3, "-", 4, "*", "-", 2, "/"]

stos = []
print(dane)
for x in dane:
	if x == "+":
		a = stos.pop()
		b = stos.pop()
		stos.append(b+a)
	elif x == "-":
		a = stos.pop()
		b = stos.pop()
		stos.append(b-a)
	elif x == "*":
		a = stos.pop()
		b = stos.pop()
		stos.append(b*a)
	elif x == "/":
		a = stos.pop()
		b = stos.pop()
		stos.append(b/a)
	else:
		stos.append(x)
print(stos)
'''


			 
#Zad 10 problem Flawiusza wyliczanka		
def Flawiusz():
	n = 10
	k = 3
	lista = list(range(1, n + 1))
	index = 0
	while len(lista) > 1:
		for _ in range(1, k):
			if (index < len(lista) - 1): index += 1;
			else: index = 0;
		print("usuwa index:", index, "liczba:", lista[index]);
		del lista[index]
		print("lista:", lista)
	return lista[0]
		
			
print(f"Zostanie ziomek {Flawiusz()}")











